language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm test
  - sonar-scanner 
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $github_token
  on:
    branch: master
notifications:
  slack: entornoicreact:7Gpp89Wywt1UTiQ2d5sYoqxQ
addons:
  sonarcloud: 
    organization: 'maxibadaro'
    token: c275e20ac3ac10885016e02cfa7808d637e4db40
